pipeline{
    agent any

    tools{
        maven "Maven"
    }
    parameters{
        text(name:'variable',defaultValue:'1', description:'Enter option 1 to test website Globant, option 2 to test Globant YouTube channel, option 3 to test Globant wikipedia website')
    }

    stages{
        stage('Downloading and compiling project'){
            steps{
                echo "compiling"
                git branch: 'test', url: 'https://github.com/MMSantiagoMM/Continuous_Integration_Jenkins_Practice_TAE.git'
                //sh 'javac src/test/java/tests/MainTest.java'

            }
        }
        stage('Executing application'){
            steps{
                echo "executing"
                //sh "java -cp src/test/java tests.MainTest -variable=${params.myVariable}"
                sh "mvn clean test -variable=${params.variable}"
                sh 'mvn -Dmaven.test.failure.ignore=true clean package'
            }
        }
    }
}